ContractorPortal/Controllers/StormdamageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContractorPortal.Controllers
{
    public class StormdamageController : Controller
    {
        // GET: Stormdamage
        public ActionResult Index()
        {
            return View();
        }
    }
}

ContractorPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        img.footerImageBBB{
             height:90px;
              width:80px;
        }

        img.footerImage{
            padding:5px;
        }
    </style>

</head>
<body>
    <div class="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("KG Roofing", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Storm Damage", "Index", "Stormdamage")</li>

                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <hr />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <img src="~/Content/IMAGES/ABC_Logo.png" class="footerImage" />

            <img src="~/Content/IMAGES/BBB.jpg" class="footerImageBBB" />
            <img src="~/Content/IMAGES/owens-corning.png" class="footerImage" />

           <p>&copy; @DateTime.Now.Year - KG Roofing and Construction</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>